services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn residencialApp.wsgi:application
    envVars:
      - key: PYTHONPATH
        value: residencialApp
      - key: DJANGO_SETTINGS_MODULE
        value: residencialApp.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
