services:
  - type: web
    name: django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn nombre_de_tu_proyecto.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nombre_de_tu_proyecto.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"